version: "3.9"
   
services:
  postgres:
    container_name: ulas-pg
    image: postgres:15-alpine
    volumes:
      - ulas_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  ulas_db: